export const ADD_BATTLE_MESSAGE = 'ADD_BATTLE_MESSAGE'
export const ADD_BATTLE_SUCCESS = 'ADD_BATTLE_SUCCESS'
export const ADD_BATTLE_ERROR = 'ADD_BATTLE_ERROR'

export const GET_BATTLE_MESSAGE = 'GET_BATTLE_MESSAGE'
export const GET_BATTLE_SUCCESS = 'GET_BATTLE_SUCCESS'
export const GET_BATTLE_ERROR = 'GET_BATTLE_ERROR'

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'